# Generated by Django 5.1.1 on 2024-09-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('nominal_power_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('maximum_power', models.DecimalField(decimal_places=2, max_digits=4)),
                ('number_of_phases', models.CharField(max_length=255)),
                ('type_of_start', models.CharField(max_length=255)),
                ('execution', models.CharField(max_length=255)),
                ('cooling_system', models.CharField(max_length=255)),
                ('type_of_installation', models.CharField(max_length=255)),
                ('machine_class', models.CharField(max_length=255)),
                ('appointment_for', models.CharField(max_length=255)),
                ('type_of_fuel', models.CharField(max_length=255)),
                ('type_of_alternator', models.CharField(max_length=255)),
                ('alternator_winding_material', models.CharField(max_length=255)),
                ('equipment', models.CharField(max_length=255)),
                ('country_of_origin_of_the_brand', models.CharField(max_length=255)),
                ('power_factor', models.DecimalField(decimal_places=2, max_digits=3)),
                ('voltage', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('rated_current_strength', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fuel_tank_capacity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fuel_consumption_litres_hour', models.DecimalField(decimal_places=2, max_digits=4)),
                ('engine_power_hp', models.DecimalField(decimal_places=2, max_digits=4)),
                ('engine_displacement', models.DecimalField(decimal_places=2, max_digits=6)),
                ('engine_speed_rpm', models.IntegerField()),
                ('volume_of_oil_in_the_engine_crankcase_litres', models.DecimalField(decimal_places=2, max_digits=4)),
                ('continuous_operation_time_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('availability_of_an_hour_meter', models.BooleanField()),
                ('degree_of_protection', models.CharField(max_length=255)),
                ('output_12_v', models.BooleanField()),
                ('height_mm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('width_mm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('warranty_months', models.IntegerField()),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
        ),
    ]
