# Generated by Django 5.1.1 on 2024-09-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('nominal_voltage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('capacity_ah', models.DecimalField(decimal_places=1, max_digits=5)),
                ('nominal_charge_current', models.DecimalField(decimal_places=1, max_digits=4)),
                ('maximum_charge_current', models.DecimalField(decimal_places=1, max_digits=4)),
                ('number_of_cycles', models.IntegerField()),
                ('operating_temperature', models.CharField(max_length=255)),
                ('height_mm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('width_mm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('depth_mm', models.DecimalField(decimal_places=1, max_digits=5)),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('warranty_months', models.IntegerField()),
                ('additional_information', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
