# Generated by Django 5.1.1 on 2024-09-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_battery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('battery_type', models.CharField(blank=True, max_length=255, null=True)),
                ('power_kw', models.DecimalField(decimal_places=2, max_digits=5)),
                ('battery_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('power_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('input_phases', models.CharField(blank=True, max_length=255, null=True)),
                ('output_phases', models.CharField(blank=True, max_length=255, null=True)),
                ('lower_input_voltage_threshold', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('upper_input_voltage_threshold', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('output_voltage', models.CharField(blank=True, max_length=255, null=True)),
                ('grid_frequency_hz', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_input_current_a', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grid_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('charging_time_ms', models.IntegerField(blank=True, null=True)),
                ('has_charger', models.BooleanField(default=False)),
                ('operating_temperature', models.CharField(blank=True, max_length=255, null=True)),
                ('humidity_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('degree_of_protection', models.CharField(blank=True, max_length=255, null=True)),
                ('height_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('width_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('depth_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('warranty_months', models.IntegerField()),
                ('type_of_execution', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='battery',
            name='depth_mm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='height_mm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='maximum_charge_current',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='nominal_charge_current',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='number_of_cycles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='operating_temperature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='warranty_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='width_mm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
