# Generated by Django 5.1.1 on 2024-09-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_inverter_alter_battery_depth_mm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortablePowerStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('nominal_power_w', models.DecimalField(decimal_places=1, max_digits=6)),
                ('peak_power_w', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('battery_type', models.CharField(max_length=255)),
                ('ac_output_voltage_v', models.CharField(blank=True, max_length=255, null=True)),
                ('dc_output_voltage', models.CharField(blank=True, max_length=255, null=True)),
                ('battery_capacity_wh', models.DecimalField(decimal_places=1, max_digits=6)),
                ('solar_charging_input', models.BooleanField(default=False)),
                ('solar_charging_input_spec', models.CharField(blank=True, max_length=255, null=True)),
                ('working_temperature_range', models.CharField(max_length=255)),
                ('height_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('width_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('depth_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('warranty_months', models.IntegerField()),
                ('usb_output_qc', models.CharField(blank=True, max_length=255, null=True)),
                ('type_c_output', models.CharField(blank=True, max_length=255, null=True)),
                ('ac_output_spec', models.CharField(blank=True, max_length=255, null=True)),
                ('dc_output_spec', models.CharField(blank=True, max_length=255, null=True)),
                ('other_ports', models.CharField(blank=True, max_length=255, null=True)),
                ('led_lamp', models.BooleanField(default=False)),
                ('wireless_charging_power_w', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('additional_information', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
