# Generated by Django 5.1.1 on 2024-10-23 15:48

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_battery_capacity_ah_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.get_image_path),
        ),
        migrations.AddField(
            model_name='generator',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.get_image_path),
        ),
        migrations.AddField(
            model_name='inverter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.get_image_path),
        ),
        migrations.AddField(
            model_name='portablepowerstation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.get_image_path),
        ),
    ]
